# Generated by Django 4.1.2 on 2022-10-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='完了フラグ'),
        ),
    ]
